### ISSUE TITLE
CLI required for build pipeline automation

### ISSUE THREAD

**Issue by wgarunap** [devopsfaith/plugin-tools#1]
Command Line Interface krakend plugin validation required when using build pipelines. It will be useful for everyone to have a **CLI**.

**Comment by kpacha** [comment]
the service offers a public API. just post your go.sum to https://plugin-tools.krakend.io/api/versions/:krakend_version/:go_version and you'll get your deps validated.

notice the endpoint returns the list of incompatibilities, so getting an empty array means that everything is ok

```
$ curl -i -d @/path/to/your/go.sum http://plugin-tools.krakend.io/api/versions/v1.3.0/1.15.8
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Cloud-Trace-Context: be08bc559e7bf2d242fa3c5e06e33237;o=1
Date: Wed, 03 Mar 2021 19:04:09 GMT
Server: Google Frontend
Content-Length: 2

[]
```

cheers!
